import Head from "next/head";
import type { NextPage } from "next";
import { makeStyles, createStyles } from "@material-ui/core/styles";

import { init } from "@assets/jss/init";
import Navbar from "@components/Navbar/Navbar";
import Banner from "@components/Banner/Banner";
import Grid from "@material-ui/core/Grid";
import Box from "@material-ui/core/Box";
import ReactPlayer from "react-player";
import Image from "next/image";
import One from "@components/Feature/One";

const useStyles = makeStyles(() =>
  createStyles({
    root: {
      // backgroundColor: "rgb(109, 78, 254)",
      backgroundColor: "#fff",
      // height: "100vh",
      width: "100%",
    },
    scalable: {
      padding: "50px 0 0",
    },
    wrapper: {
      marginLeft: "15px",
      marginRight: "-15px",
    },
    wrapLeft: {
      marginRight: "70px",
      paddingLeft: "15px",
      paddingRight: "15px"
    },
    wrapRight: {
      display: "flex",
      alignSelf: "center",
      boxSizing: "border-box",
      paddingLeft: "15px",
      paddingRight: "15px"
    },
    title: {
      boxSizing: "border-box",
      marginBottom: "20px",
      marginTop: "0px",
      maxWidth: "100%",
      fontSize: "24px",
      color: "rgb(50, 50, 93)",
      fontWeight: 700,
      lineHeight: "30px",
      letterSpacing: "-0.01em",
      "@media (min-width: 575px)": {
        fontSize: "26px",
        lineHeight: "32px",
      },
      "@media (min-width: 768px)": {
        fontSize: "30px",
        lineHeight: "40px",
      },
      "@media (min-width: 990px)": {
        fontSize: "36px",
        lineHeight: "50px",
      },
    },
    subtitle: {
      boxSizing: "border-box",
      marginBottom: "25px",
      marginTop: "0px",
      maxWidth: "100%",
      fontSize: "16px",
      color: "rgb(82, 95, 127)",
      fontWeight: 400,
      lineHeight: "28px",
      "@media (min-width: 575px)": {
        marginBottom: "25px",
      },
      "@media (min-width: 768px)": {
        marginBottom: "30px",
      },
    },
    featurewrapper: {
      display: "flex",
      flexWrap: "wrap",
      WebkitBoxPack: "justify",
      justifyContent: "space-between",
    },
    referenciaswrapper: {
      textAlign: "center",
      marginTop: "75px",
    },
    titlereferencias: {
      boxSizing: "border-box",
      marginBottom: "1rem",
      marginTop: "0px",
      fontSize: "1rem",
      color: "rgb(82, 95, 127)",
      textAlign: "center",
      lineHeight: "27px",
      fontWeight: 600,
      "@media (min-width: 575px)": {
        fontSize: "16px",
      },
      "@media (min-width: 768px)": {
        fontSize: "18px",
      },
      "@media (min-width: 990px)": {
        fontSize: "20px",
      },
    },
    reactReveal: {
      animationFillMode: "both",
      animationDuration: "1000ms",
      animationDelay: "0ms",
      animationIterationCount: "1",
      opacity: 1,
    },
  })
);

const Home: NextPage = () => {
  const classes = useStyles();
  const { containerbanner } = init();
  return (
    <>
      <div className={classes.root}>
        <Head>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Box overflow="hidden">
          <Navbar />
          <Banner />
          <section className={classes.scalable}>
            <div className={containerbanner}>
              <Grid
                container
                alignItems="center"
                className={classes.wrapper}
              >
                <Grid item xs={12} md={6}>
                  <div className={classes.wrapLeft}>
                    <div>
                      <h2 className={classes.title}>Learn how it works</h2>
                      <p className={classes.subtitle}>
                        Matched Betting is taking advantage of free bonus offers
                        from bookmakers by placing opposing bets (e.g. Liverpool
                        to win and Liverpool not to win).
                        <br />
                        That way you cannot lose, while clearing your bonuses -
                        completely risk-free!
                      </p>
                    </div>
                    <section>
                      <Grid container spacing={2}>
                        <Grid item xs={6}>
                          <One
                            src="https://d33wubrfki0l68.cloudfront.net/8141e58634979d0dee7c983c46267c18aa5d1e48/816e7/static/c552de8a2c2468c4c8b5a3e04a9a6126/jackpot.svg"
                            title="It's Risk-Free"
                            description="Learn more"
                          />
                        </Grid>
                        <Grid item xs={6}>
                          <One
                            src="https://d33wubrfki0l68.cloudfront.net/8141e58634979d0dee7c983c46267c18aa5d1e48/816e7/static/c552de8a2c2468c4c8b5a3e04a9a6126/jackpot.svg"
                            title="It's Easy to Learn"
                            description="Without prior knowledge"
                          />
                        </Grid>
                        <Grid item xs={6}>
                          <One
                            src="https://d33wubrfki0l68.cloudfront.net/8141e58634979d0dee7c983c46267c18aa5d1e48/816e7/static/c552de8a2c2468c4c8b5a3e04a9a6126/jackpot.svg"
                            title="It's Time Efficient"
                            description="Earn 30+ EUR/h"
                          />
                        </Grid>
                        <Grid item xs={6}>
                          <One
                            src="https://d33wubrfki0l68.cloudfront.net/8141e58634979d0dee7c983c46267c18aa5d1e48/816e7/static/c552de8a2c2468c4c8b5a3e04a9a6126/jackpot.svg"
                            title="It's Tax-Free"
                            description="All Profits belong to you"
                          />
                        </Grid>
                      </Grid>
                    </section>
                  </div>
                </Grid>
                <Grid item xs={12} md={6}>
                  <div className={classes.wrapRight}>
                    <ReactPlayer
                      url="http://www.youtube.com/watch?v=rG9B6uamcvc&feature=emb_title&http://localhost:3000"
                      height={315}
                      width={585}
                      config={{
                        youtube: {
                          playerVars: {
                            origin: "http://localhost:3000",
                          },
                        },
                      }}
                    />
                  </div>
                </Grid>
              </Grid>
              <div className={classes.referenciaswrapper}>
                <span className={classes.titlereferencias}>
                  Matched Betting is Well Known in the Media
                </span>
                <Grid container justifyContent="space-between" alignItems="center">
                  <Grid item xs={12} sm={6} md={4}>
                    <div className={classes.reactReveal}>
                      <a
                        href="https://www.telegraph.co.uk/finance/personalfinance/money-saving-tips/8185280/Is-this-a-bet-you-cant-lose.html"
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        <div>
                          <picture>
                            <Image
                              src="https://oddshero.io/static/2b5e92eb392d7c63eb6f797f05f4f157/61e93/press-telegraph.webp"
                              width={200}
                              height={70}
                              alt="telegraph"
                            />
                          </picture>
                        </div>
                      </a>
                    </div>
                  </Grid>
                  <Grid item xs={12} sm={6} md={4}>
                    <div className={classes.reactReveal}>
                      <a
                        href="https://www.telegraph.co.uk/finance/personalfinance/money-saving-tips/8185280/Is-this-a-bet-you-cant-lose.html"
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        <div>
                          <picture>
                            <Image
                              src="https://oddshero.io/static/2b5e92eb392d7c63eb6f797f05f4f157/61e93/press-telegraph.webp"
                              width={200}
                              height={70}
                              alt="telegraph"
                            />
                          </picture>
                        </div>
                      </a>
                    </div>
                  </Grid>
                  <Grid item xs={12} sm={6} md={4}>
                    <div className={classes.reactReveal}>
                      <a
                        href="https://www.telegraph.co.uk/finance/personalfinance/money-saving-tips/8185280/Is-this-a-bet-you-cant-lose.html"
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        <div>
                          <picture>
                            <Image
                              src="https://oddshero.io/static/2b5e92eb392d7c63eb6f797f05f4f157/61e93/press-telegraph.webp"
                              width={200}
                              height={70}
                              alt="telegraph"
                            />
                          </picture>
                        </div>
                      </a>
                    </div>
                  </Grid>
                  <Grid item xs={12} sm={6} md={4}>
                    <div className={classes.reactReveal}>
                      <a
                        href="https://www.telegraph.co.uk/finance/personalfinance/money-saving-tips/8185280/Is-this-a-bet-you-cant-lose.html"
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        <div>
                          <picture>
                            <Image
                              src="https://oddshero.io/static/2b5e92eb392d7c63eb6f797f05f4f157/61e93/press-telegraph.webp"
                              width={200}
                              height={70}
                              alt="telegraph"
                            />
                          </picture>
                        </div>
                      </a>
                    </div>
                  </Grid>
                  <Grid item xs={12} sm={6} md={4}>
                    <div className={classes.reactReveal}>
                      <a
                        href="https://www.telegraph.co.uk/finance/personalfinance/money-saving-tips/8185280/Is-this-a-bet-you-cant-lose.html"
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        <div>
                          <picture>
                            <Image
                              src="https://oddshero.io/static/2b5e92eb392d7c63eb6f797f05f4f157/61e93/press-telegraph.webp"
                              width={200}
                              height={70}
                              alt="telegraph"
                            />
                          </picture>
                        </div>
                      </a>
                    </div>
                  </Grid>
                </Grid>
              </div>
            </div>
          </section>
        </Box>
      </div>
    </>
  );
};

export default Home;
